services:
  - type: web
    name: AccSell
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --workers=1 --threads=2 --timeout=120 --bind=0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SERVER_NUMBER
        value: 4
